import type { Metadata } from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";
import { cn } from "@/lib/utils";
import {SiteHeader} from "@/components/site-header";
import {SiteFooter} from "@/components/site-footer";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Sphereal AI",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: ReactNode}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(inter.className, "antialiased")}>
      <main className="flex flex-col min-h-screen">
        <SiteHeader />
        {children}
        <SiteFooter />
      </main>
      </body>
    </html>
  );
}
